kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-admin-9d6eac9d70673425
  namespace: kafka
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
