---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: rhsso-dev
  labels:
    app: rhsso-dev
  namespace: rhsso-dev
spec:
  disableReplicasSyncing: true
# disable the Replica sync in order to use the HPA for scalling
  multiAvailablityZones:
    enabled: true
# we add this flag for HA deploy, we need more than 1 pod for this
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 2
# we set a minimum of 2 pods for the HA
  storageClassName: gp2